### ISSUE TITLE
可以通过更改应用签名的方式在OPPO&ColorOS上使用吗?

### ISSUE THREAD

**Issue by boillter** [BinTianqi/AndroidOwner#5]
具体可见[https://github.com/iamr0s/Dhizuku/discussions/16#oppo_sign](url)，Dhizuku能够通过这种方式获取到ColorOS的设备所有者权限

**Comment by boillter** [comment]
[链接发错了](https://github.com/iamr0s/Dhizuku/discussions/16#oppo_sign)

**Comment by WoAiNianChu** [comment]
> [链接发错了](https://github.com/iamr0s/Dhizuku/discussions/16#oppo_sign)

可以的，我已经成功了
