### ISSUE TITLE
ColorOS 成功使用

### ISSUE THREAD

**Issue by WoAiNianChu** [BinTianqi/AndroidOwner#6]
![Screenshot_2024-04-16-16-50-45-72_fc704e6b13c4fb26bf5e411f75da84f2.png](https://github.com/BinTianqi/AndroidOwner/assets/112552691/75668ddc-ea04-4991-bba0-bf9c591df9e3)

![Screenshot_2024-04-16-16-50-32-51_cfb2bb30ca5583806d6e59637d60195d.png](https://github.com/BinTianqi/AndroidOwner/assets/112552691/6d00b757-ade1-44ec-a8fb-a8640720386c)

目前我已经通过用mt管理器自签名该App实现了获取设备所有者（DeviceOwner）
参考[帖子](https://www.coolapk.com/feed/53531416)

**Comment by BinTianqi** [comment]
以前我只知道颜色OS的Device owner需要是白名单，现在才知道debug签名也行。
下次release会有debug签名的apk

**Comment by WoAiNianChu** [comment]
> 以前我只知道颜色OS的Device owner需要是白名单，现在才知道debug签名也行。
> 下次release会有debug签名的apk

**刚刚测试新发布的debug的签名不可以激活。**_mt的默认签名依旧可以。_
建议发布是出一个用mt默认签名的或者直接发布一个无签名版本让用户用mt自签名.

**Comment by BinTianqi** [comment]
问题应该是，这个调试签名是Android Studio生成的，每个人都不一样

**Comment by WoAiNianChu** [comment]
> 我发的那个调试签名是Android Studio生成的，每个人都不一样。
> mt管理器那个默认签名是一样的。我没mt，用apktoolm签了个名，跟mt的应该一样，签名发布日期2008年。

应该是一样的，mt默认签名创建时间也为2008。
![Screenshot_2024-04-16-21-38-07-42_9e8df3d0c7c1f50248b6ee043a653d26.png](https://github.com/BinTianqi/AndroidOwner/assets/112552691/ed357e1c-a9bb-4d19-ac8c-d96a75688a92)

**Comment by BinTianqi** [comment]
找到那个[2008年的签名](https://cs.android.com/android/platform/superproject/main/+/main:build/make/target/product/security/)了，我用testkey签了个名，你试试能不能用。

[testkey-debug.zip](https://github.com/BinTianqi/AndroidOwner/files/14998403/testkey-debug.zip)

（躺在床上用手机编译的debug版，很卡，测试完换回你自己签名的release版吧）

**Comment by WoAiNianChu** [comment]
> 找到那个[2008年的签名](https://cs.android.com/android/platform/superproject/main/+/main:build/make/target/product/security/)了，我用testkey签了个名，你试试能不能用。
> 
> [testkey-debug.zip](https://github.com/BinTianqi/AndroidOwner/files/14998403/testkey-debug.zip)
> 
> （躺在床上用手机编译的debug版，很卡，测试完换回你自己签名的release版吧）
> （应该是能用的，签名md5跟你的一样）

测试可用，激活成功。

**Comment by boillter** [comment]
> 找到那个[2008年的签名](https://cs.android.com/android/platform/superproject/main/+/main:build/make/target/product/security/)了，我用testkey签了个名，你试试能不能用。
> 
> [testkey-debug.zip](https://github.com/BinTianqi/AndroidOwner/files/14998403/testkey-debug.zip)
> 
> （躺在床上用手机编译的debug版，很卡，测试完换回你自己签名的release版吧） （应该是能用的，签名md5跟你的一样）

大佬能发下签名文件么，我没找到下载链接😢

**Comment by BinTianqi** [comment]
去release啊

**Comment by boillter** [comment]
主要还是自己手动签名比较放心

**Comment by boillter** [comment]
就是那个testkey.pk8
