### ISSUE TITLE
[Invalid / Documentation] The activation command in Guide.md seems to be incorrect

### ISSUE THREAD

**Issue by MinoriceOwO** [BinTianqi/AndroidOwner#7]
### Describe the issue
There seems to be a small issue in the Guide.md: the activation command for Device Admin / Profile Owner / Device Owner is incorrect. In Guide.md, the activation command for Device Admin / Profile Owner / Device Owner is written as `adb shell dpm set-(active-admin || profile-owner || device-owner) com.binbin.androidowner/com.binbin.androidowner.MyDeviceAdminReceiver`. In fact, the receiver `com.binbin.androidowner.MyDeviceAdminReceiver` is not registered. Users executing the wrong activation command will receive an error, which could lead to some confusion.

### Expected result
The correct receiver should be `com.binbin.androidowner.dpm.MyDeviceAdminReceiver` (as it is displayed within the app). Therefore, the activation command should be updated to `adb shell dpm set-(active-admin || profile-owner || device-owner) com.binbin.androidowner/com.binbin.androidowner.dpm.MyDeviceAdminReceiver` instead.

**Comment by BinTianqi** [comment]
I forgot to update documentation after the device admin receiver moved to `com.binbin.androidowner.dpm` package

**Comment by BinTianqi** [comment]
你不是会说中文吗？

Why you speak English? 

😂

**Comment by MinoriceOwO** [comment]
草, 被发现了 ()
只是感觉在 gh 上用英文发 Issue 会显得规范一些 (划
